version: '3'
services:
  mzda:
    container_name: mzda-app
    image: mzda:latest
    ports:
      - "8080:8080"  # Expose port 8080 on the host to port 8080 in the container
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres  # Use the service name as the database host
      POSTGRES_PORT: 5432      # Use the default port for PostgreSQL
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - bridge-net

  postgres:
    container_name: mzda-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bridge-net

networks:
  bridge-net:
    driver: bridge

volumes:
  postgres_data:
