version: '3'
services:
  mzda:
    container_name: mzda-app
    image: mzda:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres  # Use the service name as the host
      POSTGRES_PORT: 5432      # Use the default PostgreSQL port
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - bridge-net

  postgres:
    container_name: mzda-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "55000:5432"  # Map host port 55000 to container port 5432
    networks:
      - bridge-net

networks:
  bridge-net:
    driver: bridge

volumes:
  postgres_data:
